# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '53 0 * * *' # Daily at 00:53 UTC
  workflow_dispatch:

jobs:
  build:
    name: Build charm
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v22.0.0
    with:
      cache: true

  integration-test:
    name: Integration
    needs:
      - build
    uses: canonical/data-platform-workflows/.github/workflows/integration_test_charm.yaml@test-runners-2
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
      architecture: amd64
      cloud: lxd
      juju-agent-version: 3.4.5
      _beta_allure_report: true
      _default-runner: '["self-hosted", "linux", "X64", "large", "jammy"]'
    secrets:
      integration-test: |
        {
          "AWS_ACCESS_KEY": "${{ secrets.AWS_ACCESS_KEY }}",
          "AWS_SECRET_KEY": "${{ secrets.AWS_SECRET_KEY }}",
          "GCP_ACCESS_KEY": "${{ secrets.GCP_ACCESS_KEY }}",
          "GCP_SECRET_KEY": "${{ secrets.GCP_SECRET_KEY }}",
          "UBUNTU_PRO_TOKEN" : "${{ secrets.UBUNTU_PRO_TOKEN }}",
          "LANDSCAPE_ACCOUNT_NAME": "${{ secrets.LANDSCAPE_ACCOUNT_NAME }}",
          "LANDSCAPE_REGISTRATION_KEY": "${{ secrets.LANDSCAPE_REGISTRATION_KEY }}",
        }
    permissions:
      contents: write  # Needed for Allure Report beta
